<?php
/**
 * Created by PhpStorm.
 * User: bizou
 * Date: 22/11/17
 * Time: 16:48
 */

namespace WCS\CoavBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\BirthdayType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;

class RegistrationType extends AbstractType{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $builder
            ->add('firstName', TextType::class, array(
                'attr' => array(
                    'label' => 'Prenom'
                )
            ))
            ->add('lastName', TextType::class, array(
                'attr' => array(
                    'label' => 'Nom'
                )
            ))
            ->add('phoneNumber', NumberType::class, array(
                'attr' => array(
                    'label' => 'Mobile'
                )
            ))
            ->add('birthDate', BirthdayType::class, array(
                'attr'  => array(
                    'label' => 'Date de naissance'
                )
            ))
            ->add('note', NumberType::class, array(
                'attr'  => array(
                    'label' => 'note'
                )
            ))
            ->add('isACertifiedPilot')
            ->add('isActive')
            ->add('creationDate', DateType::class, array(
                'data'  => new \DateTime('now')
            ));
    }

    public function getParent()
    {
        //return parent::getParent(); // TODO: Change the autogenerated stub
        return 'FOS\UserBundle\Form\Type\RegistrationFormType';
    }

    public function getBlockPrefix()
    {
        //return parent::getBlockPrefix(); // TODO: Change the autogenerated stub
        return 'wcs_user_registration';
    }

    public function getName(){
        return $this->getBlockPrefix();
    }
}